local _, T = ...
-- See https://www.townlong-yak.com/addons/opie/localization

local C, z, V, K = GetLocale(), nil
V =
    C == "ruRU" and { -- 214/215 (100%)
      "%d |4минуту:минуты:минут; назад (%s)", "%s для отмены", "%s для поиска в текущих результатах", "(Все комплекты)", "(по умолчанию)", "(введите название иконки или путь к ней)", "Создать кольцо", "Добавить новый фрагмент", "Дополнительная прокрутка после использования", "Все персонажи   %s",
      "Все параметры", "Все персонажи", "Разрешить быстрое применение", "Нажать Alt для установки условной привязки", z, "Анимировать переходы", "Анимация", "Все внесенные изменения в настоящее время не будут сохраняться.", "Внешний вид", "Привязать ко всем специализациям",
      "В позиции всплывающей подсказки HUD", "В центре кольца", "Нажмите, чтобы изменить иконку", "Поведение", "Противоречие назначения горячей клавиши", "Назначение клавиши:", "Отмена", "Изменить действие", "Изменения не будут сохранены", "Выберите горячую клавишу для этого кольца, или включите опцию %s в настройках OPie.",
      "Закрыть кольцо", "Закрыть кольцо после быстрого действия", "Цвет:", "Бой", "Условные привязки", "Противоречие с: %s", "Скопируйте URL, указанный выше, и откройте его в веб-браузере.", "Создать профиль", "Создание Нового профиля", "Создание нового кольца",
      "Создать новый профиль", "Пользовательские Кольца", "Пользовательский сегмент", "Настройте OPie путем изменения существующих колец, или создайте Ваше собственное.", "Настройте привязки клавиш OPie ниже. |cffa0a0a0Gray|r и |cffFA2800red|r привязки конфликтуют с другими и в настоящее время не активны.", "Настраивайте кольцо OPie и параметры привязки клавиш в кольце.", "Настройте внешний вид и поведение OPie.", "Настройте внешний вид и поведение OPie. ПКМ по флажку восстанавливает его в состояние по умолчанию.", "Модификация назначенных клавиш", "Пользовательские привязки клавиш внутри кольца",
      "Модификация настроек", "Кастомизация иконки", "Назначение клавиш по умолчанию отключено", "По умолчанию", "По умолчанию для всех колец", "Удалить текущий профиль", "Удалить кольцо", "Удалить фрагмент", "Отключено", "Отображение фрагмента перехода",
      "Отображать как вложенное кольцо", "Отображать как:", "Не показывать", "Ничего не делать", "Вы точно хотите вернуть все настройки %s к значениям по умолчанию или только настройки в категории %s?", "Редактируйте существующие или создавайте собственные кольца OPie.", "Встраивать в другие кольца по умолчанию", "Вставить часть в это кольцо", "Пустое кольцо", "Увеличивать выбранный фрагмент",
      "Комплекты экипировки", "Пример: %s.", "Скрытые кольца", "Скрыть панель стоек", "Скрыть это кольцо", "Иконка:", "Если что-то в OPie работает неправильно (или вы хотите, чтобы оно работало по-другому), создайте обсуждение проблемы, перейдя по ссылке:", "Если кольцо уже открыто:", "Если условия этого макроса равны %s, или если его условия неприменимы, то этот раздел будет спрятан.", "Импортировать %s |4вложенное кольцо:вложенные кольца;",
      "Импорт снимка", "Импортируйте снимки, нажав %s выше.", "Внутренние привязки клавиш кольца", "Неактивные кольца", "Включая вложенные кольца", "Введите спецификацию действия для сегмента:", "Установите обновленную версию этого внешнего вида, чтобы выбрать его.", "Установите и включите %s для поиска по имени файла.", "Мгновенное вращение указателя", "Взаимодействие",
      "Не сворачивать после использования", "Клик левой кнопкой, чтобы назначить привязку", "Сделать это кольцо доступным:", "Отслеживание на миникарте", "Без мыши", "Перемещение кольца по вертикали", "Перемещение кольца по горизонтали", "Вложенное кольцо: %s", "Многоуровневые кольца", "Новое кольцо...",
      "Новое имя профиля:", "Ничего", "Не назначено", "Не настраиваемое для каждого кольца.", "Не перенастроено", "Не поддерживается выбранным внешним видом.", "OPie Кольцо", "OPie кольцо: %s", "OPie кольца", "По клику левой:",
      "По клику правой:", "По нажатию на привязанную клавишу кольца:", "По отпусканию привязанной клавиши кольца:", "Только %s", "Открыть вложенное кольцо", "Открыть кольцо под курсором", "Открыть кольцо по центру экрана", "Параметры", "Параметры:", "Увеличивать спираль при сворачивании",
      "Переопределить иконку", "Переопределить ярлык:", "Путь закаленного героя", "Ротации кольца для каждого персонажа.", "Использовать клавиши цифр", "Использовать клавиши цифр:", "Предварительный выбор быстрого действия для фрагмента", "Нажмите %s для сохранения.", "Нажмите %s для поиска", "Показывать кольцо поверху",
      "Профиль", "Профили сохраняют параметры и привязку клавиш.", "Предметы для заданий", "Быстрый", "Быстрое действие в центре кольца", "Быстрое действие если мышь остаётся неподвижной", "Быстрое действие для повторения активации:", "Случайная ротация после использования", "Рандомизировать ротацию на экране", "Спокойный",
      "Запомнить последнюю ротацию", "Открыть кольцо снова", "Сообщить о проблеме", "Сбрасывать поворот при отображении", "Перезапустите World of Warcraft. Если это сообщение продолжает появляться, удалите и переустановите OPie.", "Восстановить по умолчанию", "Восстановить настройки по умолчанию", "Восстановить удалённое кольцо", "Вернуться...", "ПКМ чтобы отвязать",
      "Назначения клавиш для колец", "Название кольца:", "Масштаб кольца", "На стороне кольца", "Кольцо: %s", "Вращение:", "Прокрутка внутреннего кольца (вниз)", "Прокрутка внутреннего кольца (вверх)", "Поиск", "Выберите %s действия для включения данной опции",
      "Выберите кольцо для изменения", "Дважды щелкните, чтобы добавить в кольцо.", "Выбранный отрезок(закрыть кольцо)", "Выбранный отрезок(оставить кольцо открытым)", "Установить фильтр имени:", "Поделиться кольцом", "Shift + клик для того чтобы увидеть макро команды кольца", "Показывать время востановления", "Показать время восстановления", "Показать названия фрагментов",
      "Показать этот фрагмент для:", "Показать всплывающие подсказки", "Имитировать ПКМ", "Фрагмент #%d", "Привязка сектора конфликтует с %s.", "Снимок:", "Для обозначения иконки введите имя файла, путь к текстуре, имя атласа, или известное имя способности", "Сделайте снимок этого кольца, чтобы поделиться им с другими.", "Метка цели", "Привязка будет обновлена чтобы отразить значение этого выражения параметров макроса.",
      "Следующие макро команды открывают это кольцо:", "Этот раздел", "Это отображение может не поддерживать все возможности OPie.", "Данное сочетание клавиш уже используется другим аддоном.", "Данное сочетание клавиш неактивно, так как конфликтует с другим сочетанием.", "Профессиональные навыки", "Срабатывание по нажатию клавиши", "Срабатывание при отпускании клавиши", "Понятно;всё равно изменить", "Отменить изменения",
      "Неподвижный курсор", "Неподвижный курсор, или в центре кольца", "Требуется обновление", "Использовать привязку  для колец по умолчанию", "Использовать первый фрагмент при открытии", "Использовать глобальные настройки", "Использовать фрагмент", "Использовать фрагмент и закрыть кольцо", "Видимые условия:", "Когда кольцо открыто:",
      "World of Warcraft не удалось загрузить сохраненные переменные OPie из-за нехватки памяти. Попробуйте отключить другие аддоны.", "Вы можете отменить или вернуть предыдущие настройки позже.", "Вы можете использовать расширенные макро условия; см. %s.", "Вы должны включить опцию %s для этого кольца в настройках OPie для использования быстрых действий.", "Ваш персонаж не может использовать это в данный момент.", "по умолчанию", "Адаптация", "Благодарности", "Отблагодарить", "Поддержать дальнейшую разработку можно здесь:",
      "%s — автор оригинального аддона.", "%s — адаптация для World of Warcraft 3.3.5a.", "%s — оптимизация под Sirus.", "Только высший ранг", "Метки на местности",
    } or nil

K = V and {
      "%d |4minute:minutes; ago (%s)", "%s to cancel", "%s to search within current results", "(All sets)", "(default)", "(enter an icon name or path here)", "Add Ring", "Add a new slice", "Advance rotation after use", "All %s characters",
      "All Settings", "All characters", "Allow as quick action", "Alt click to set conditional binding", "An error occurred while loading OPie.", "Animate transitions", "Animation", "Any changes you make now will not be saved.", "Appearance", "Assign to all specializations",
      "At HUD Tooltip position", "At ring center", "Based on slice action", "Behavior", "Binding conflict", "Binding:", "Cancel", "Change action", "Changes will not be saved", "Choose a binding for this ring, or enable the %s option in OPie options.",
      "Close ring", "Close ring after quick action", "Color:", "Combat", "Conditional Bindings", "Conflicts with: %s", "Copy the URL shown above and visit it using a web browser.", "Create Profile", "Create a New Profile", "Create a New Ring",
      "Create a new profile", "Custom Rings", "Custom slice", "Customize OPie by modifying existing rings, or creating your own.", "Customize OPie key bindings below. Hover over a binding button for additional information and options.", "Customize OPie ring and in-ring key bindings.", "Customize OPie's appearance and behavior.", "Customize OPie's appearance and behavior. Right clicking a checkbox restores it to its default state.", "Customize bindings", "Customize in-ring bindings",
      "Customize options", "Customized icon", "Default binding disabled", "Defaults", "Defaults for all rings", "Delete current profile", "Delete ring", "Delete slice", "Disabled", "Display a jump slice",
      "Display as a nested ring", "Display as:", "Do not show", "Do nothing", "Do you want to reset all %s settings to their defaults, or only the settings in the %s category?", "Edit existing rings, or create your own custom OPie rings.", "Embed into other rings by default", "Embed slices in this ring", "Empty ring", "Enlarge selected slice",
      "Equipment Sets", "Example: %s.", "Hidden rings", "Hide stance bar", "Hide this ring", "Icon:", "If something in OPie does not behave correctly (or if you'd like it to behave differently), create an issue by visiting:", "If the ring is already open:", "If this macro options expression evaluates to %s, or if none of its clauses apply, this slice will be hidden.", "Import %s |4nested ring:nested rings;",
      "Import snapshot", "Import snapshots by clicking %s above.", "In-Ring Bindings", "Inactive rings", "Include nested rings", "Input a slice action specification:", "Install an updated version of this appearance to select it.", "Install and enable %s to search by file name.", "Instant pointer rotation", "Interaction",
      "Leave open after use", "Left click to assign binding", "Make this ring available to:", "Minimap Tracking", "Mouse-less", "Move rings down", "Move rings right", "Nested ring: %s", "Nested rings", "New Ring...",
      "New profile name:", "None", "Not bound", "Not configurable per-ring.", "Not customized", "Not supported by selected appearance.", "OPie Ring", "OPie ring: %s", "OPie rings", "On left click:",
      "On right click:", "On ring binding press:", "On ring binding release:", "Only %s", "Open nested ring", "Open ring at mouse", "Open ring at screen center", "Options", "Options:", "Outward spiral on hide",
      "Override Icon", "Override label:", "Path of the Seasoned Hero", "Per-character ring rotations", "Per-slice bindings", "Per-slice bindings:", "Pre-select a quick action slice", "Press %s to save.", "Press %s to search", "Prevent other UI interactions",
      "Profile", "Profiles save options and ring bindings.", "Quest Items", "Quick", "Quick action at ring center", "Quick action if mouse remains still", "Quick action repeat trigger:", "Randomize rotation after use", "Randomize rotation on display", "Relaxed",
      "Remember last rotation", "Reopen ring", "Report an Issue", "Reset rotation on display", "Restart World of Warcraft. If this message continues to appear, delete and re-install OPie.", "Restore default", "Restore default settings", "Restore deleted ring", "Revert...", "Right click to unbind",
      "Ring Bindings", "Ring name:", "Ring scale", "Ring-side", "Ring: %s", "Rotation:", "Scroll nested ring (down)", "Scroll nested ring (up)", "Search", "Select a %s interaction to enable this option.",
      "Select a ring to modify", "Select an action by double clicking.", "Selected slice (close ring)", "Selected slice (keep ring open)", "Set name filter:", "Share ring", "Shift click to view ring macro command", "Show cooldown numbers", "Show recharge numbers", "Show slice labels",
      "Show this slice for:", "Show tooltips:", "Simulate a right-click", "Slice #%d", "Slice binding conflicts with %s.", "Snapshot:", "Specify an icon by entering an icon file name, texture path, atlas name, or a known ability name.", "Take a snapshot of this ring to share it with others.", "Target Markers", "The binding will update to reflect the value of this macro options expression.",
      "The following macro command opens this ring:", "These Settings", "This appearance may not support all OPie features.", "This binding is currently used by another addon.", "This binding is not currently active because it conflicts with another.", "Trade Skills", "Trigger on binding press", "Trigger on binding release", "Understood; edit anyway", "Undo changes",
      "Unmoved cursor", "Unmoved cursor, or at ring center", "Update required", "Use default ring bindings", "Use first slice when opened", "Use global setting", "Use slice", "Use slice and close ring", "Visibility conditional:", "While a ring is open:",
      "World of Warcraft could not load OPie's saved variables due to a lack of memory. Try disabling other addons.", "You can cancel or revert to previous settings later.", "You may use extended conditionals; see %s for details.", "You must enable a %s interaction for this ring in OPie options to use quick actions.", "Your character currently cannot use this.", "default", "Adaptation", "Credits", "Donate", "You can support further development by visiting:",
      "%s — author of the original addon.", "%s — adaptation for World of Warcraft 3.3.5a.", "%s — optimization for Sirus.", "Highest ranks only", "World Markers",
}

local L = K and {}
for i=1,K and #K or 0 do
	L[K[i]] = V[i]
end

T.L = L or nil