name: Luacheck

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: luacheck-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install luacheck
        run: |
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends lua-check
          luacheck --version

      - name: Run luacheck
        run: luacheck .
